# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_MAJOR: 3
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_MAJOR: 2
      PYTHON_ARCH: "32"

# scripts that run after cloning repository
install:
  # Ensure python scripts are from right version:
  - 'SET "PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%"'
  # Install coverage utilities:
  - 'pip install codecov'
  # Install our package:
  - 'pip install --upgrade -e ".[test]"'

build: off

# to run your custom scripts instead of automatic tests
test_script:
  - 'py.test -l --cov-report xml:"%APPVEYOR_BUILD_FOLDER%\coverage.xml" --cov=globmatch'

on_success:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - codecov -X gcov --file "%APPVEYOR_BUILD_FOLDER%\coverage.xml"
